version: '3.8'

services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - 8080:8000
    env_file:
      - web_vars.env
    depends_on:
      - db
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=async_5

volumes:
  postgres_data: